app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings
from app.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/',views.product, name='product'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/',views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users_cart/', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),
    path('change_password/', views.ChangePassword.as_view(), name='change_password'),
    path('reset_password/', views.ResetPassword.as_view(), name='reset_password'),
    path('reset_password_done/', views.ResetPasswordDone.as_view(), name='reset_password_done'),
    path('reset_password/confirm/<uidb64>/<token>/', views.ResetPasswordConfirm.as_view(), name='reset_password_confirm')

]

orders/models.py
from django.db import models
from goods.models import Products

from users.models import User


class OrderitemQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="User",
                             default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Order creation date")
    phone_number = models.CharField(max_length=20, verbose_name="Phone number")
    requires_delivery = models.BooleanField(default=False, verbose_name="Delivery required")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Delivery address")
    payment_on_get = models.BooleanField(default=False, verbose_name="Payment upon receipt")
    is_paid = models.BooleanField(default=False, verbose_name="Paid")
    status = models.CharField(max_length=50, default='In processing', verbose_name="Order status")

    class Meta:
        db_table = "order"
        verbose_name = "Order"

    def __str__(self):
        return f"Order № {self.pk} | Buyer {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Order")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Product",
                                default=None)
    name = models.CharField(max_length=150, verbose_name="Name")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Price")
    quantity = models.PositiveIntegerField(default=0, verbose_name="quantity")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Date of sale")

    class Meta:
        db_table = "order_item"
        verbose_name = "Sold item"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Product {self.name} | Order № {self.order.pk}"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    image =models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Avatar')
    phone_number = models.CharField(max_length=12, blank=True, null=True)

    class Meta:
        db_table = 'user'
        verbose_name_plural = 'users'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, PasswordChangeForm
from  .models import  User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'autofocus': True,
                                      'class': 'form-control',
                                      'placeholder': 'Enter your username'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password',
                                          'class': 'form-control',
                                          'placeholder': 'Enter your password'})

    )
    class Meta:
        model = User
        fields = ['username', 'password']


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()
    password1 = forms.CharField()
    password2 = forms.CharField()


    # first_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': 'Enter your  name',
    #         }
    #     )
    # )
    # last_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': 'Enter your last name',
    #         }
    #     )
    # )
    # username = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': 'Enter your username',
    #         }
    #     )
    # )
    # email = forms.EmailField(
    #     widget=forms.EmailInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': 'Enter your email address',
    #         }
    #     )
    # )
    # password1 = forms.CharField(
    #     widget=forms.PasswordInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': 'Enter your password',
    #         }
    #     )
    # )
    # password2 = forms.CharField(
    #     widget=forms.PasswordInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': 'Enter your password',
    #         }
    #     )
    # )

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'image',
            'first_name',
            'last_name',
            'username',
            'email',)

    image = forms.ImageField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

users/views.py
from django.contrib import auth, messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView, PasswordResetView, PasswordResetConfirmView,PasswordResetDoneView
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView

from carts.models import Cart
from orders.models import Order, OrderItem
# from django.contrib.auth.models import  User
from .forms import UserLoginForm, UserRegisterForm, ProfileForm
from .models import User


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                messages.success(request, f'{username},You are now logged in')

                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

                redirect_page = request.POST.get("next", None)
                if redirect_page and redirect_page != reverse("user:logout"):
                    return HttpResponseRedirect(request.POST.get('next'))

                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()
    context = {
        'title': 'Home - Authorization',
        'form': form
    }
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            auth.login(request, user)

            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)

            messages.success(request, f'{user.username},You are now registered')
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegisterForm()

    context = {
        'title': 'Home - Registration',
        'form': form
    }
    return render(request, 'users/registration.html', context)


# class UserRegister(FormView):
#     template_name = 'users/registration.html'
#     form_class = UserRegisterForm
#     success_url = reverse_lazy('users:login')

# def form_valid(self, form):
#     form.save()
#     return super().form_valid(form)

@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated!')
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = ProfileForm(instance=request.user)

    orders = (
        Order.objects.filter(user=request.user)
        .prefetch_related(
            Prefetch(
                "orderitem_set",
                queryset=OrderItem.objects.select_related("product"),
            )
        )
    ).order_by("-id")

    context = {
        'title': 'Home - Profile',
        'form': form,
        'orders': orders
    }

    return render(request, 'users/profile.html', context)


def users_cart(request):
    return render(request, 'users/users_cart.html')


@login_required
def logout(request):
    messages.success(request, f'{request.user.username},You are now logged out')
    auth.logout(request)
    return redirect(reverse('main:index'))



class ChangePassword(PasswordChangeView):
    template_name = "users/password_change.html"
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        messages.success(self.request, f'{self.request.user.username} Your password has been changed successfully.')
        return super().form_valid(form)

class ResetPassword(PasswordResetView):

    template_name = 'users/reset_password.html'
    success_url = reverse_lazy('users:reset_password_done')

class ResetPasswordDone(PasswordResetDoneView):

    template_name = 'users/reset_password_done.html'


class ResetPasswordConfirm(PasswordResetConfirmView):

    template_name = 'users/reset_password_confirm.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        messages.success(self.request, f'{self.request.user.username} Your password has been reset successfully.')
        return super().form_valid(form)

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Authorization</h2>
                <form action="{% url 'users:login' %}" method="post">
                    {% csrf_token %}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value={{request.GET.next}}>
                    {% endif %}

                    <div class="mb-3">
                        <label for="{{ form.username.id_for_label }}" class="form-label">Username</label>
                       {{ form.username}}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.password.id_for_label }}" class="form-label">Password</label>
                       {{form.password}}
                    </div>

                    <!--                    <div class="mb-3">-->
                    <!--                        <label for="username" class="form-label">Имя пользователя</label>-->
                    <!--                        <input type="text" class="form-control" id="username"-->
                    <!--                               placeholder="Введите ваше имя пользователя" required>-->
                    <!--                    </div>-->
                    <!--                    <div class="mb-3">-->
                    <!--                        <label for="password" class="form-label">Пароль</label>-->
                    <!--                        <input type="password" class="form-control" id="password" placeholder="Введите ваш пароль"-->
                    <!--                               required>-->
                    <!--                    </div>-->
                    <button type="submit" class="btn btn-dark btn-block">Log in</button>
                </form>
                <div class="mt-3">
                    <a href="{% url 'users:reset_password' %}">Forgot password?</a> | <a href="{% url 'user:registration' %}">Create account</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Or authorizate here:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'deps/icons/google.svg' %}" alt="Catalog Icon" width="16"
                             height="16">
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'deps/icons/facebook.svg' %}" alt="Catalog Icon" width="16"
                             height="16">
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'deps/icons/github.svg' %}" alt="Catalog Icon" width="16"
                             height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_change.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row mt-5 justify-content-center">
            <div class="col-md-6 bg-white p-5 rounded shadow-sm">
                <h2 class="text-center mb-4">Change Password</h2>

                <form action="{% url 'users:change_password' %}" method="post">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                    <div class="mb-3">
                        {{ form.old_password.label_tag }}
                        {{ form.old_password }}
                        {% for error in form.old_password.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-3">
                        {{ form.new_password1.label_tag }}
                        {{ form.new_password1 }}
                        {% for error in form.new_password1.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-3">
                        {{ form.new_password2.label_tag }}
                        {{ form.new_password2 }}
                        {% for error in form.new_password2.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <button type="submit" class="btn btn-dark btn-block">Change Password</button>
                </form>

                <hr>
                <div class="text-center">
                    <p>Remembered your password? <a href="{% url 'users:login' %}" class="text-decoration-none">Login here</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профиль пользователя</h3>
                    <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {% if user.image %}
                                    <img src="{{ user.image.url }}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% else %}
                                    <img src="{% static "deps/images/baseavatar.jpg" %}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image"
                                    name='image'
                                    accept="image/*">
                                    {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name"
                                    placeholder="Введите ваше имя"
                                    value="{{ form.first_name.value }}"
                                    required>
                                    {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    name="last_name"
                                    placeholder="Введите вашу фамилию"
                                    value="{{ form.last_name.value }}"
                                    required>
                                    {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="id_username"
                                    name="username"
                                    placeholder="Введите ваше имя пользователя"
                                    value="{{ form.username.value }}"
                                    required>
                                    {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    name="email"
                                    placeholder="Введите ваш email *youremail@example.com"
                                    value="{{ form.email.value }}"
                                    required>
                                    {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Сохранить</button>
                        <a href="{% url 'users:change_password' %}" class="btn btn-dark">Change Password</a>
                    </form>
                </div>
            </div>
            <!-- Корзина -->
            {% user_carts request as carts %}

            <div class="col-md-7">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Корзина</h3>
                    <div class="container" id="cart-items-container">
                        <!-- Разметка корзины -->
                        {% include "carts/includes/included_cart.html" %}
                        <!-- Закончилась разметка корзины -->
                    </div>
                </div>
            </div>
            <!-- Оформленные заказы -->
            <div class="col-md-12">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Мои заказы</h3>
                    <!-- Разметка заказов -->
                    <div class="container">
                        <div class="accordion" id="accordionExample">
                            {% for order in orders %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading{{ order.id }}">
                                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                        Заказ № {{ order.id }} - {{ order.created_timestamp }} | Статус: <strong class="mx-2">{{order.requires_delivery}}</strong>
                                    </button>
                                </h2>
                                <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in order.orderitem_set.all %}
                                                <tr>
                                                    <td><a class="text-white" href="{% url 'goods:product' item.product.slug %}">{{ item.product.name }}</a></td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td>{{ item.price }}</td>
                                                    <td>{{ item.products_price }}</td>

                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% comment %} <div class="container">
                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading1">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
                                        Заказ № 256 - 09 сентября 2023 9:04 | Статус:<strong class="mx-2"> В обработке</strong>
                                    </button>
                                </h2>
                                <div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><a class="text-white" href="#">Комплект стол и три стула</a></td>
                                                    <td>1</td>
                                                    <td>255.00 $</td>
                                                    <td>255.00 $</td>

                                                </tr>
                                            </tbody>
                                        </table>
                                        <div class="d-flex justify-content-between">
                                            <p><strong>Итого:</strong></p>
                                            <p><strong>255.00 $</strong></p>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading2">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
                                        Заказ № 248 - 01 августа 2023 11:28 | Статус: <strong>Получен</strong>
                                    </button>
                                </h2>
                                <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><a class="text-white" href="#">Стул офисный</a></td>
                                                    <td>2</td>
                                                    <td>30.00 $</td>
                                                    <td>60.00 $</td>

                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> {% endcomment %}
                    <!-- Закончилась разметка заказов -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

users/templates/users/reset_passsword_done.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row mt-5 justify-content-center">
            <div class="col-md-80 bg-white p-5 rounded shadow-sm">
                <h2 class="text-center mb-4">Reset Password</h2>
                <p class="text-center mb-4">We have emailed you instructions to reset your password. Please check your email.</p>
                <hr>
                <div class="text-center">
                    <a href="{% url 'users:login' %}" class="btn btn-dark">Back to Login</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}